### ISSUE TITLE
Improve the response time of the data when making new selections

### ISSUE THREAD

**Issue by almccon** [americanpanorama/panorama-foreignborn#13]

**Comment by ebrelsford** [comment]
I've found that changing the query on [this line](https://github.com/americanpanorama/panorama-foreignborn/blob/master/app/apis/app.js#L13) by removing `RTRIM()` makes the query ~2x faster, which makes the transition happen that much faster when clicking on counties.

Is this something we can take care of on the table itself (`UPDATE`ing `nhgis_join` with `RTRIM(nhgis_join)`)? I'd be curious to also try adding an index on the `nhgis_join` column to see how that affects response time.

**Comment by ebrelsford** [comment]
Between 04bfea88 and the index on `nhgis_join` that I added (`CREATE INDEX idx_site_foreignborn_county_breakdowns_materialized_nhgis_join ON site_foreignborn_county_breakdowns_materialized (nhgis_join)`), selecting a new county is between 2 and 3x faster.

**Comment by ebrelsford** [comment]
@almccon Any selections I'm missing that should be speedier?

**Comment by almccon** [comment]
Wow, feels much faster to me! So you didn't need to remove the `RTRIM()` then, and just improved it with the index?

**Comment by ebrelsford** [comment]
@almccon I did both removing `RTRIM()` and adding the index, but the index is the big improvement here. I'm not sure if the `RTRIM`-less version is live, but it's slightly quicker.

**Comment by emilyhobson** [comment]
Closed?

**Comment by ebrelsford** [comment]
I'd be okay with closing it, @almccon do you think it's quick enough now or is there anything else I should look at?
