### ISSUE TITLE
Consider adding a tutorial

### ISSUE THREAD

**Issue by almccon** [americanpanorama/panorama-foreignborn#15]
See also https://github.com/americanpanorama/panorama-forcedmigration/issues/8

**Comment by emilyhobson** [comment]
Foreign born

Intro panel: At all points in its history, a significant proportion of the population of the United States had been born in other countries and regions. This being the case, American history can never be understood by just looking within its borders. The culture and politics of the US have always been profoundly shaped by the material and emotional ties many of its residents have had to the places where they were born. This map will allow you to begin to explore those connections at the basic level of demographic statistics.
1. Use the map to see where the foreign-born as a whole or for a selected country were concentrated. Select a county by clicking on it.

Could we add HIGHER population density and LOWER population density to 1?
1. The grean circles show the number of immigrants from that country or region. Click on them to select the country.
2. The charts shows how the foreign-born population of a selected county compared to the US as a whole or how it changed for a selected country.
3. See which country had the largest foreign-born population during a given decade.

This map uses census data to visualize the evolving places immigrants came from and where they came to from the mid-nineteenth century to today.

**Comment by nicolettehayes** [comment]
Looks like we need shorter descriptions on 1, 3 and 4.

optimal:
![screen shot 2016-08-15 at 4 46 17 pm](https://cloud.githubusercontent.com/assets/12550451/17683504/38ddc986-6308-11e6-9400-d557256f2853.png)
(two lines for 1, three lines for 2, three lines for 3, 2 lines for 4)

with latest copy:
![screen shot 2016-08-15 at 4 34 28 pm](https://cloud.githubusercontent.com/assets/12550451/17683505/3cec8972-6308-11e6-939d-c01804432bdb.png)
(cut two lines from 1, one line from 3, and one line from 4.)

Also, I would advise against adding anymore instruction to the graphic in number 1--the information provided was intended as a hook, not an exhaustive explanation. For that thorough explanation (which I don't anticipate users thinking to ask for until they have tried using it anyway), I would suggest adding a line about high and low population density within the text of the "i" function:
![screen shot 2016-08-15 at 4 47 06 pm](https://cloud.githubusercontent.com/assets/12550451/17683501/319d310c-6308-11e6-99ad-6b48e46de936.png)

**Comment by sconnelley** [comment]
![image](https://cloud.githubusercontent.com/assets/565486/17787983/610b7522-6540-11e6-974e-d17714202a21.png)

![image](https://cloud.githubusercontent.com/assets/565486/17787994/6da20a58-6540-11e6-9616-59aff0726860.png)
