### ISSUE TITLE
CRITICAL: Site load blocked due to mixed content

### ISSUE THREAD

**Issue by wboykinm** [americanpanorama/panorama-foreignborn#18]
Apparently some of the content is coming in over non-hhtps wires. Chrome and safari both block data from the site now:

![site](https://www.dropbox.com/s/2usn3bn2jb5jk0z/Screenshot%202017-01-31%2012.58.37.png?dl=1)

**Comment by rnelson2** [comment]
Should now be loadable over https

**Comment by wboykinm** [comment]
Confirmed. Thanks!
