### ISSUE TITLE
typo in 1970 about text

### ISSUE THREAD

**Issue by almccon** [americanpanorama/panorama-foreignborn#4]
"after Fidel Castro camp to power"

![screen shot 2016-02-06 at 6 feb 3 21 11](https://cloud.githubusercontent.com/assets/1212178/12870008/5e341816-cce5-11e5-9451-e7a8b8e4a551.png)

**Comment by almccon** [comment]
I won't have a chance to fix this for a few days... maybe @rnelson2 or @jmadron will beat me to it, and redeploy.

**Comment by jmadron** [comment]
I fixed the error and committed it. Rob-- do you mind redeploying?

**Comment by jmadron** [comment]
fixed and redeployed.
