### ISSUE TITLE
Overlapping circles in legend are a different color than overlapping circles on map

### ISSUE THREAD

**Issue by almccon** [americanpanorama/panorama-foreignborn#7]
Are these different blend modes or something?
<img width="482" alt="screen shot 2016-02-23 at 12 44 46 pm" src="https://cloud.githubusercontent.com/assets/1212178/13266237/edae8d0c-da2b-11e5-98be-e822dc8f4ccf.png">

**Comment by almccon** [comment]
Even worse, I guess some users thought that those circles were transitioning between green and blue, which makes sense based on the blue used elsewhere in the interface.

**Comment by ebrelsford** [comment]
Took a stab at this, giving the circles white strokes to match the rest of the interface:

![selection_001](https://cloud.githubusercontent.com/assets/375002/13794593/0dd7fffc-ead3-11e5-8e6d-c56545aa591a.png)
